name: flutter_belgium
description: A flutter app for the belgian flutter community
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  ai_barcode_scanner: ^3.4.1
  confetti: ^0.7.0
  cloud_firestore: ^4.13.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.0
  flutter_navigation_generator_annotations: ^1.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  provider: ^6.0.5
  retrofit: ^4.0.3
  rxdart: ^0.27.0
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_navigation_generator: ^1.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/