name: flutter_belgium
description: The Flutter Belgium app to connect with the community.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  confetti: ^0.7.0
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_remote_config: ^4.3.14
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.0
  flutter_localizations:
    sdk: flutter
  flutter_navigation_generator_annotations: ^1.0.1
  impaktfull_architecture: ^0.0.10
  json_annotation: ^4.8.1
  sprintf: ^7.0.0
  rxdart: ^0.27.0
  uuid: ^4.2.2
  webview_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_navigation_generator: ^1.0.4+1
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  locale_gen: ^12.1.2
  impaktfull_cli: ^0.14.1

dependency_overrides:
  impaktfull_ui: 
    path: /Users/vanlooverenkoen/work/open_source/impaktfull/flutter_impaktfull_ui
  impaktfull_architecture: 
    path: /Users/vanlooverenkoen/work/open_source/impaktfull/flutter_architecture

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/font/ubuntu/
    - assets/locale/
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu/ubuntu_regular.ttf

locale_gen:
  default_language: 'en'
  languages: ['en']