name: flutter_belgium
description: The Flutter Belgium app to connect with the community.
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  confetti: ^0.8.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_remote_config: ^5.3.0
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.2
  flutter_localizations:
    sdk: flutter
  flutter_navigation_generator_annotations: ^2.1.0
  impaktfull_architecture: ^0.8.1
  impaktfull_ui: ^0.30.0
  json_annotation: ^4.9.0
  phosphor_flutter: ^2.1.0
  sprintf: ^7.0.0
  rxdart: ^0.28.0
  uuid: ^4.5.1
  webview_flutter: ^4.10.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_navigation_generator: ^2.1.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  locale_gen: ^12.1.4
  impaktfull_cli: ^0.15.3

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/font/ubuntu/
    - assets/locale/
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu/ubuntu_regular.ttf

locale_gen:
  default_language: "en"
  languages: ["en"]
